### ISSUE TITLE
Gossip Todo

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/lightning#127]
This is a tracking issue for the gossip overhaul for the new architecture.

 - [X] Implement staggered broadcast for peers that are owned by `gossipd`
 - [X] Forward gossip messages to owner if `gossipd` is not the owner
 - [x] Create announcements for newly created channels
  - [x] Implement the `getnodes` JSON-RPC call
 - [x] Implement the `getroute` JSON-RPC call
- [x] Implement the `getchannels` JSON-RPC call
 - [x] Add a new callback to wait for 6 confirmations before sending `announcement_signatures`
 - [x] Generate valid signatures for the announcements using the HSM #138 

Depending on the decision on #126, we also need to

 - [ ] Increase size of internal messages from `u16` to `u32` (might need some additional refactoring since currently we simply reuse the external wire format).
