### ISSUE TITLE
Tracking issue: Bolt 12 compatibility

### ISSUE THREAD

**Issue by vincenzopalazzo** [ElementsProject/lightning#7407]
# Tracking issue

This issue is trying to summarize all the issue that are stopping the BOLT 12 compatibility
with other implementation

- [ ] https://github.com/ElementsProject/lightning/issues/7402
- [ ] https://github.com/ElementsProject/lightning/issues/7404
- [ ] https://github.com/ElementsProject/lightning/issues/7405 
- [ ] https://github.com/ElementsProject/lightning/issues/7401
- [ ] https://github.com/ElementsProject/lightning/issues/7382
